name: build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-14, macos-15-intel]
        build_type: [Release]
        staticcompile: [ON, OFF]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Install dependencies for Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -yq build-essential cmake pkg-config \
          libgmp-dev zlib1g-dev libboost-program-options-dev libboost-test-dev

    - name: Install dependencies for Mac
      if: contains(matrix.os, 'macos')
      run: brew install automake libtool boost pkg-config gmp

    - name: Build m4ri and BRiAl
      uses: ./.github/actions/build-deps
      with:
        static: ${{ matrix.staticcompile }}

    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.staticcompile }}

    - name: Configure & build
      run: |
        mkdir -p build && cd build
        cmake \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DSTATICCOMPILE=${{ matrix.staticcompile }} \
          -DENABLE_TESTING=ON \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
          ..
        cmake --build . --config ${{ matrix.build_type }}

    - name: Run it to check it executes
      run: ./build/bosphorus --version

    - name: Test
      run: ctest -C ${{ matrix.build_type }} --verbose
      working-directory: build

    - name: Upload Artifact
      if: matrix.staticcompile == 'ON'
      uses: actions/upload-artifact@v4
      with:
        name: bosphorus-${{ matrix.os }}
        path: build/bosphorus
